### ISSUE TITLE
How to debug scrape failures?

### ISSUE THREAD

**Issue by stiller-leser** [moznion/resque_exporter#4]
Hi,

first off: Thanks for writing this. I am having troubles getting this to run though. The only thing that increases for me are the 'resque_exporter_scrape_failures_total' - but how can I debug why the exporter is failing? 

Here is my configuration:

```
resque_namespace: 'resque:admin_server'
guard_interval_millis: 0
redis:
    host: 10.1.1.1
    port: 6379
    db: 0
    password: notimportant
```
What do I do if I do not have any password? If I connect with `redis-cli -h 10.1.1.1 -a` I really could put anything into the space behind the `-a`. 

Thanks ahead for your support!

**EDIT:**
Ok so I just taught myself go and how to setup your project... Turns out that the password does matter. So I guess I would need to prepare a pull request that tests wether or not a password is defined and based on the results opens the redis connection.

**EDIT2:**
So it turns out if password is set to an empty string '', it works fine. It even works with an empty space, but not with any arbitrary phrase like the redis-cli. A `log.Fatal(err)` above line 103 in exporter.go would help a lot though. This way the resque_exporter would show errors, which would be really helpful.
